spring:
  application:
    name: platform
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/base?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

server:
  port: 7000
  servlet:
    context-path: /platform

wx:
  loginurl: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code

zlp:
  system:
    name: platform
    platform-url: http://127.0.0.1:7000
  login:
    permit-url: /platform/sso,/platform/file,/platform/log/record,/platform/msg
  log:
    permit-url: /platform/log/record

minio:
  endpoint: http://127.0.0.1:9000
  accessKeyId: root
  accessKeySecret: 123456

msg:
  token: 11