// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Sign: typeof import('./src/components/Sign.vue')['default']
    UpdateInfo: typeof import('./src/components/UpdateInfo.vue')['default']
  }
}

export { }
